# Form implementation generated from reading ui file '/media/nemsys/data/projects/courses/netIT/PythonCourseNetIT/PythonCourse_27.02.2023-Labs/lab39/MyFirstGUIProject/calculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 518)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 30, 401, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setToolTip("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(0, 120, 391, 71))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 361, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_1 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pb_1.setEnabled(True)
        self.pb_1.setObjectName("pb_1")
        self.horizontalLayout_2.addWidget(self.pb_1)
        self.pb_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pb_2.setEnabled(True)
        self.pb_2.setObjectName("pb_2")
        self.horizontalLayout_2.addWidget(self.pb_2)
        self.pb_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pb_3.setObjectName("pb_3")
        self.horizontalLayout_2.addWidget(self.pb_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:36pt; font-weight:700;\">Calculator</span></p></body></html>"))
        self.pb_1.setText(_translate("Form", "1"))
        self.pb_2.setText(_translate("Form", "2"))
        self.pb_3.setText(_translate("Form", "3"))
